const ActionTypes = {
  SUBMIT_BOOK_FAIL: "SUBMIT_BOOK_FAIL",
  LOAD_BOOK_FAIL: "LOAD_BOOK_FAIL",
  FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAIL: "DELETE_BOOK_FAIL"
};

export default ActionTypes;
